# "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmFjYTgwZGJhYzQ5OTA5N2UxNzMwMCIsImlhdCI6MTcxNjkxODE3Mn0.pVRbPc10DU9j9RjSNze1iVTAt7sEziN5qk8niRoUsmo"


GET http://localhost:3000/new-notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmFjYTgwZGJhYzQ5OTA5N2UxNzMwMCIsImlhdCI6MTcxNjkxODE3Mn0.pVRbPc10DU9j9RjSNze1iVTAt7sEziN5qk8niRoUsmo
